name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npm run migrate:up

      - name: Run unit/API tests (Vitest)
        run: npm test --silent

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests (Playwright)
        env:
          CI: true
        run: npm run e2e --silent

      - name: Build web
        run: npm run build --silent
